//
//  SignReport.swift
//  Twinkle
//
//  Created by Micky Chettanapanich on 2/2/20.
//  Copyright © 2020 Twinkle. All rights reserved.
//

import Foundation

var moonSignData = [
    "Aquarius":"It's a good time to think about how your personal choices affect society and humanity as a whole. You could spend time with your group of friends discussing how you can work together support each other and the wider world by bringing in change. If we all do something we can make a difference.",
    "Pisces":"Sleep late and write down your dreams - if you can find a pen and paper that is. Otherwise just go back to sleep, turn off your mobile, your phone and retreat into your inner world. It's only by listening to our dreams that we find out who we might be. If you're suffering and in pain today, you can develop compassion and empathy for all those in a similar or worse situation. Maybe this will give you the impetus to do something to help them. If you can get up and you're not too disappointed by the sad state of real world, going to a film or the sea is a good thing to do today. Don't worry if you don't achieve a lot in the outside world.",
    "Aries":"When the Moon is in Aries, anger and assertion are more likely to be expressed openly over these two days but it's a quick flare-up and things will soon settle down. You won't feel like compromising. It's also a good time for starting things off and putting energy into going after your own personal goals. You might feel more competitive than usual and it's easy to step on other people's toes at this time. Be careful not to rush into things you might regret later, Aries can be very impulsive.",
    "Taurus":"With the Moon in Taurus it's a good time for shopping and indulgence. Buy yourself a new perfume, flowers and fruit! If you can, spend some time in the country breathing clean air, and appreciating the beauties of Mother Nature. If you're in a city go to the park and sit on the grass. At home, put your feet up, put on your new album, light some candles and have a long bath scented with aromatherapy oils. Indulge in some good food, and gentle, sensual massage with your lover.",
    "Gemini":"With the Moon in Gemini get up early, listen to the news and get out of the house. This is a good day for travelling about and visiting people you haven't seen for a while. If you can't actually meet up, then text or phone your friends, family, colleagues. If you're at work it can be a good day for meetings but be careful that you don't get so bogged down by so much information that you lose sight of the bigger picture. You might want to get a new book and spend the evening on the internet.",
    "Cancer":"Don't go anywhere today if you can possibly avoid it. Have a nice day at home making your personal space your sanctuary. Cook a wonderful meal and gather your family round. Looking after children or elderly relatives would be good things to do today. Otherwise you might just want to work through some of your feelings which you didn't have time to deal with before. These days are good for some rest and recuperation.",
    "Leo":"With the Moon in Leo you have the opportunity to celebrate yourself. You are special and unique. Wear that outfit that announces to the world that you're a star. If you haven't got that outfit yet - go out and get it. It's a good time to have a party, or go to the theatre. Children and the inner child are important for these days as Leo likes to play. Leo is the sign of creativity and love affairs so go for it now.",
    "Virgo":"Doing some useful work is the best way to use the energy of the Moon in Virgo. It might be studying, writing that report you've been meaning to get down to, organising your office, tidying your home or doing the garden. Anything that needs sorting out should be done today when you will get satisfaction from it and it won't feel like such a chore. If you know anyone who could do with a helping hand then this is the time to go to their assistance. It's also a good time to improve your health - these two days would be good for a monthly detox or you could go to the gym, or health club.",
    "Libra":"These two days are for you and your partner or friends to get together and spend some quality time with each other. If there has been any strife, this is a good time to bring harmony back to the situation. You are more able to understand each other's point of view right now. Pleasant conversation and lively discussions are both likely today as testing the validity of ideas is part of the balancing energy of Libra. Generally it's a good time to socialise in beautiful, environments, playing or listening to music, dancing, reading poetry aloud, or visiting an art gallery together.",
    "Scorpio":"If you've been sitting on any negative feelings, then the Moon in Scorpio will bring these to the forefront and give you that extra impetus to confront them. Deep, hidden issues come up around this time and when we really examine them and feel them to the full, they lose their hold over us. It's better to spend these two days quietly working through our own stuff. If you have to go out, be aware that it's easier to project negativity onto others rather than dealing with it ourselves so be careful not to become a target or to pick on anyone unjustifiably. If you're in any kind of therapy, make your appointments for these days.",
    "Sagittarius": "Jump out of bed and go for a long run before getting on your bike and cycling to work. Get those legs working! If you can take the day off, you might like to get a day return somewhere you haven't been before, just to see what it's like. If you can't get away, then it's a good day to expand your mind by studying some philosophical ideas or religious beliefs. You might like to go to a museum or library and check out some heavy tomes! In the evening you'll probably feel like going out for a curry, a Thai or Chinese and a few drinks. The tendency will be to overdo it on all levels. You might stay up too late and wake up with a hangover. Never mind, take a few Paracetamol and carry on tomorrow - life's too short.",
    "Capricorn":"The good times can't last forever and there are bills to be paid. The serious side of life is to the fore over the next couple of days. Where have you been ducking your responsibilities? This is the time to get everything sorted out and settled before things get out of hand. Time to set some boundaries for yourself and others to make sure that everyone is clear about what's expected. Career figures prominently - your place in the world needs to be maintained and it's only by hard work, thoroughly carried out that you can stay at the top of your game."
]

var sunSignData = [
    "Aquarius":"Aquarius-born are shy and quiet , but on the other hand they can be eccentric and energetic. However, in both cases, they are deep thinkers and highly intellectual people who love helping others. They are able to see without prejudice, on both sides, which makes them people who can easily solve problems. Although they can easily adapt to the energy that surrounds them, Aquarius-born have a deep need to be some time alone and away from everything, in order to restore power. People born under the Aquarius sign, look at the world as a place full of possibilities.",
    "Pisces":"Pisces are very friendly, so they often find themselves in a company of very different people. Pisces are selfless, they are always willing to help others, without hoping to get anything back.",
    "Aries":"The presence of Aries always marks the beginning of something energetic and turbulent. They are continuously looking for dynamic, speed and competition, always being the first in everything - from work to social gatherings. It is in their nature to take action, sometimes before they think about it well.",
    "Taurus":"Practical and well-grounded, Taurus is the sign that harvests the fruits of labor. They feel the need to always be surrounded by love and beauty, turned to the material world, hedonism, and physical pleasures. People born with their Sun in Taurus are sensual and tactile, considering touch and taste the most important of all senses. Stable and conservative, this is one of the most reliable signs of the zodiac, ready to endure and stick to their choices until they reach the point of personal satisfaction.",
    "Gemini":"Expressive and quick-witted, Gemini represents two different personalities in one and you will never be sure which one you will face. They are sociable, communicative and ready for fun, with a tendency to suddenly get serious, thoughtful and restless. They are fascinated with the world itself, extremely curious, with a constant feeling that there is not enough time to experience everything they want to see.",
    "Cancer":"Deeply intuitive and sentimental, Cancer can be one of the most challenging zodiac signs to get to know. They are very emotional and sensitive, and care deeply about matters of the family and their home. Cancer is sympathetic and attached to people they keep close. Those born with their Sun in Cancer are very loyal and able to empathize with other people's pain and suffering.",
    "Leo":"People born under the sign of Leo are natural born leaders. They are dramatic, creative, self-confident, dominant and extremely difficult to resist, able to achieve anything they want to in any area of life they commit to. There is a specific strength to a Leo and their \"king of the jungle\" status. Leo often has many friends for they are generous and loyal. Self-confident and attractive, this is a Sun sign capable of uniting different groups of people and leading them as one towards a shared cause, and their healthy sense of humor makes collaboration with other people even easier.",
    "Virgo":"People born under the sign of Leo are natural born leaders. They are dramatic, creative, self-confident, dominant and extremely difficult to resist, able to achieve anything they want to in any area of life they commit to. There is a specific strength to a Leo and their \"king of the jungle\" status. Leo often has many friends for they are generous and loyal. Self-confident and attractive, this is a Sun sign capable of uniting different groups of people and leading them as one towards a shared cause, and their healthy sense of humor makes collaboration with other people even easier.",
    "Libra":"People born under the sign of Libra are peaceful, fair, and they hate being alone. Partnership is very important for them, as their mirror and someone giving them the ability to be the mirror themselves. These individuals are fascinated by balance and symmetry, they are in a constant chase for justice and equality, realizing through life that the only thing that should be truly important to themselves in their own inner core of personality. This is someone ready to do nearly anything to avoid conflict, keeping the peace whenever possible",
    "Scorpio":"Scorpio-born are passionate and assertive people. They are determined and decisive, and will research until they find out the truth. Scorpio is a great leader, always aware of the situation and also features prominently in resourcefulness. Scorpio is a Water sign and lives to experience and express emotions. Although emotions are very important for Scorpio, they manifest them differently than other water signs. In any case, you can be sure that the Scorpio will keep your secrets, whatever they may be.",
    "Sagittarius":"Curious and energetic, Sagittarius is one of the biggest travelers among all zodiac signs. Their open mind and philosophical view motivates them to wander around the world in search of the meaning of life. Sagittarius is extrovert, optimistic and enthusiastic, and likes changes. Sagittarius-born are able to transform their thoughts into concrete actions and they will do anything to achieve their goals.",
    "Capricorn":"Capricorn is a sign that represents time and responsibility, and its representatives are traditional and often very serious by nature. These individuals possess an inner state of independence that enables significant progress both in their personal and professional lives. They are masters of self-control and have the ability to lead the way, make solid and realistic plans, and manage many people who work for them at any time. They will learn from their mistakes and get to the top based solely on their experience and expertise."]


var compatability = [
    "Aries":"Aries, Leo Sagittarius, Gemini, Libra, Aquarius",
    "Leo":"Aries, Leo Sagittarius, Gemini, Libra",
    "Sagittarius":"Aries, Leo Sagittarius, Gemini, Libra, Aquarius",
    "Taurus":"Taurus, Virgo, Capricorn, Cancer, Scorpio, Pisces",
    "Virgo":"Taurus, Virgo, Capricorn, Cancer, Scorpio",
    "Capricorn":"Taurus, Virgo, Capricorn, Cancer, Scorpio, Pisces",
    "Gemini":"Aries, Leo, Gemini, Libra, Aquarius",
    "Libra":"Leo, Sagittarius, Gemini, Libra, Aquarius",
    "Aquarius":"Aries, Leo, Sagittarius, Gemini, Libra, Aquarius",
    "Cancer":"Taurus, Virgo, Capricorn, Cancer, Scorpio, Pisces",
    "Scorpio":"Taurus, Virgo, Capricorn, Cancer, Scorpio, Pisces",
    "Pices":"Taurus, Capricorn, Cancer, Scorpio, Pisces"
]
